### ISSUE TITLE
Pagination and ui issues

### ISSUE THREAD

**Issue by NutanNiraula** [rv928/SurveyApp#1]
@rv928 Hi, it seems you have not implemented pagination in the app, the api should be capable of providing paginated results. Also, could you please check some UI issues in the app like 
1. image getting compressed, 
2. safe area gap for last item,
3. status bar color and 
4. button animation, notice that when we tap on the button it does not respond to the press by dimming

I have attached a image for your reference.

![screenshot](https://i.imgur.com/OkStebk.gif)

**Comment by rv928** [comment]
@NutanNiraula ,
Thanks for your review and inputs for my submitted code. sorry for these bugs.
I fixed above bugs with branch (bug/ColorAndAnimation) and merged into develop branch. Now you can check latest code with improved UI and bug fixes.

**Comment by NutanNiraula** [comment]
@rv928 Hi, thank you so much for addressing the issues. 🙏  I checked out latest develop but the image stretching issue is still there, looks like you have now added the safe area space but ideally it would be nice to have the images full screen and only fix the extra spacing on the last item, also, notice that after adding pagination the horizontal page indicator does not update and showing an activity indicator on top of the UI blocks the UI and user input, (the last one is kind of nitpick, sorry 😅 ). 

![screenshot](https://i.imgur.com/JMtJGA5.gif)

I am going to provide you my review to start a discussion. Please take this as a two way process and feel free to share examples, additional context or even raise concerns on each of these. This is nowhere near an exhaustive list but things I noticed while I skimmed through your code. The goal is to understand your decision process.

1.  One thing I noticed was that you were using swifty JSON over swift's Encodable/Decodable, it's not to judge it as good or bad but I would love to know your opinion on it. It's completely open ended discussion so, please feel free to share your opinion.

2. Another thing I noticed was there were empty files in survey detail. I would like to know your opinion on creating template and following a set architecture and having empty files or breaking the pattern to just use MVC, for example how would you approach a thank you page that has no additional functionality at all? Again, this is a open question so, there is no right/wrong, I just want to know your opinions.

3. You have not used any linters, what is your opinion on swiftLint for example?

4. There are couple of interesting decisions I see in your implementation, I just want you to know that I appreciate those like for example you have tried to use test spys and seeds, UI tests and accessibility identifiers were nice touch. Adding keychain, and adding a interceptor layer for retrying and header adaption were nice. You removed the default comments and cleaned up files like in appDelegates and viewcontrollers that was nice. ✌️  

5. One thing I wanted to specifically tell you was to use enum instead of structs to organize namespaces for static constants. Can you tell me why I would say something like that? What would be the difference between struct and enum in this case?

6. Your tests were crashing when I tried to run. I want to know your opinion about the automation in projects, like CI/CD. What do you think are important in considering automation and defining good process?

**Comment by rv928** [comment]
@NutanNiraula  Hello,
Thanks for reviewing my latest update. Kindly check new code from develop.

Though i surprised you are able to see pagecontrol on screen after last update and even from my previous code, i am not able to see in my screen simulator (may be some glitch or bug with simulator). so i updated code on assumption basis for pagecontrol count. I fixed bug about image stretch, safe area full screen, page indicator count (array updated). Sorry i have not given interaction to pagecontrol dots.
